version: '3'
services:
  app:
    build:
      context: ./app  # Ruta hacia el backend (FastAPI)
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}  # URL para conectar a MongoDB Atlas
    ports:
      - '8000:8000'  # Expone el servicio FastAPI en el puerto 8000
